### ISSUE TITLE
BUG: undefined package(), before() and share(). Does not support Laravel 5.6

### ISSUE THREAD

**Issue by waiylkarim** [jenssegers/laravel-ab#10]
Jenssegers\AB\TesterServiceProvider:

```
line 25: undefined method package()

line 28: undefined method before()

line 41: undefined method share()
```

**Package not compatible with Laravel 5.4 and Laravel 5.6**

**Comment by ben182** [comment]
@waiylgeek I published a new [package ](https://github.com/ben182/laravel-ab) for ab testing that supports laravel 5.

**Comment by waiylkarim** [comment]
@ben182 Thank you. And maybe you should update README.md to point new comers to the new package.
