### ISSUE TITLE
Is it possible to run multiple experiments simultaneously?

### ISSUE THREAD

**Issue by nevets963** [jenssegers/laravel-ab#5]
It doesn't apear this is possible - if not, what could be done to make this possible?

**Comment by rafelsanso** [comment]
You can create few experiments like this:

    'experiments' => [
        'homepage_test1',
        'homepage_test2',
        'contactpage_test1',
        'contactpage_test2',
    ],

And then, in the page `"homepage"` you can use the experiment:

    @if (AB::experiment('homepage_test1'))
        Hello!
    @elseif (AB::experiment('homepage_test2'))
        World!
    @endif

And the same in `contact page`:

    @if (AB::experiment('contactpage_test1'))
        Hello contact!
    @elseif (AB::experiment('contactpage_test2'))
        Contact World!
    @endif

**Comment by saulsharma** [comment]
@jenssegers any updates on this?

**Comment by sergeich5** [comment]
great idea
